---
- hosts: all
  gather_facts: false
  connection: smart

  vars_prompt:
    - name: ansible_user
      prompt: Username
      private: no
    - name: ansible_password
      prompt: Password
      private: yes
      
  vars:
    provider:
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      server: "{{ inventory_hostname }}"
      validate_certs: no
      server_port: 443
      
  group_vars:
    service:
      - name: <some_name_of_service>
        content_file: <local_file>
        partition: <partition>
        chain: <certificate chain>
        passphrase: <passphrase_file>
        sync_group: <HA_sync>

  collections: f5networks.f5_modules

  tasks:
    - block: 
      - name: Show active status 
        bigip_command:
          provider: "{{ provider }}"
          commands: show /cm failover-status
        register: failover
  
      - name: Active Status Assertion
        assert:
          that: "'ACTIVE' in failover.stdout_lines[0][4]"

      - name: Import SSL Private Key
        bigip_ssl_key:
          provider: "{{ provider }}"
          name: "{{ item.name }}"
          content: "{{ lookup('file', './files/<local_file>') }}" 
          partition: "{{ item.partition }}"
        loop: "{{ service }}"

      - name: Import SSL Certificate
        bigip_ssl_certificate:
          provider: "{{ provider }}"
          name: "{{ item.name }}"
          content: "{{ lookup('file', './files/<local_file>') }}" 
          partition: "{{ item.partition }}"
        loop: "{{ service }}"

      - name: Create New Client SSL Profile
        bigip_profile_client_ssl:
          provider: "{{ provider }}"
          name: "clientsslpf-{{ item.name }}"
          partition: "{{ item.partition }}"
          cert_key_chain:
            - cert: "{{ item.name }}"
              key: "{{ item.name }}"
              chain: "{{ item.chain }}"
              passphrase: "{{ lookup('file', './files/<passphrase_file>') }}" 
        loop: "{{ service }}"

      # Save system configuration and sync to group
      - name: Save Configuration and Sync to Standby
        bigip_configsync_action:
          provider: "{{ provider }}"
          device_group: "{{ sync_group }}"
          sync_device_to_group: yes
      
      delegate_to: localhost
