---
- hosts: all
  gather_facts: false
  connection: local
 
  vars_prompt:
    - name: ansible_user
      prompt: Username
      private: no
    - name: ansible_password
      prompt: Password
      private: yes
      
  vars:
    provider:
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      server: "{{ inventory_hostname }}"
      validate_certs: no
      server_port: 443
 
  group_vars:
    pool_members:
      partition: Common
      pool: f5-pool-name
      pool_members:
        - name: pool-member-1
          address: 1.1.1.1
          port: 443
          state: enabled # options: enabled, disabled, forced_offline
      
        - name: pool-member-1
          address: 2.2.2.2
          port: 443
          state: enabled # options: enabled, disabled, forced_offline

  collections:
    - f5networks.f5_modules

  tasks:
    - block: 
      - name: Show Active Status
        bigip_command:
          provider: "{{ provider }}"
          commands: show /cm failover-status
        register: failover

      - name: Active Status Assertion
        assert:
          that: "'ACTIVE' in failover.stdout_lines[0][4]"

      - name: Enable/Disable/Force Offline F5 Pool Members
        bigip_pool_member:
          provider: "{{ provider }}"
          partition: "{{ partition }}"
          pool: "{{ pool }}"
          name: "{{ item.name }}"
          address: "{{ item.address }}"
          port: "{{ item.port }}"
          state: "{{ item.state }}"
        loop: "{{ pool_members }}"
      
      - name: Save Configuration and Sync to Standby
        bigip_configsync_action:
          provider: "{{ provider }}"
          device_group: "{{ sync_group }}"
          sync_device_to_group: yes

      delegate_to: localhost
